set github_version
ome/scc pull request #283
Opened 2023-04-18 07:02 UTC by jburel

The introduction of ``github_version`` like https://github.com/ome/conda-bioformats2raw/blob/master/bioformats2raw/meta.yaml#L3 breaks the scheduled build preventing the automatic bump of version

2023-04-18 07:54 UTC, sbesson requested changes
Using the HEAD of this branch and the current state of `conda-bioformats2raw`, I get


```diff
(base) sbesson@Sebastiens-MacBook-Pro-2 conda-bioformats2raw % git show
commit e89940f8de85fe1257b00136cc4f7df9429c0fb3 (HEAD -> master)
Author: Sébastien Besson <sbesson@glencoesoftware.com>
Date:   Tue Apr 18 08:47:42 2023 +0100

    Update version to 0.6.1

diff --git a/bioformats2raw-libs/meta.yaml b/bioformats2raw-libs/meta.yaml
index ba1e8b0..4038ee5 100644
--- a/bioformats2raw-libs/meta.yaml
+++ b/bioformats2raw-libs/meta.yaml
@@ -1,5 +1,5 @@
 {% set name = "bioformats2raw-libs" %}
-{% set version = "0.5.0" %}
+{% set version = "0.6.1" %}
 {% set github_version = "0.5.0" %}
 
 package:
@@ -11,17 +11,18 @@ build:
   noarch: generic
 
 source:
-  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version }}/bioformats2raw-{{ github_version }}.zip
-  sha256: 23f88a70c6ee94998e08420a465f8497b6da561488ac1dc3f56335c9763064d0
+  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version
+    }}/bioformats2raw-{{ github_version }}.zip
+  sha256: ca821ffb2a357a4ae15afd1c17848c4acd2ca905013183ad7ceb7b4e4b50643d
 
 # Leave the OS specific dependencies to the wrapper
 requirements:
   run:
-    - blosc
+  - blosc
 
 extra:
   recipe-maintainers:
-    - ome
+  - ome
 
 about:
   home: https://www.glencoesoftware.com/
diff --git a/bioformats2raw/meta.yaml b/bioformats2raw/meta.yaml
index 3fb45ef..0a78a95 100644
--- a/bioformats2raw/meta.yaml
+++ b/bioformats2raw/meta.yaml
@@ -1,5 +1,5 @@
 {% set name = "bioformats2raw" %}
-{% set version = "0.5.0" %}
+{% set version = "0.6.1" %}
 {% set github_version = "0.5.0" %}
 
 package:
@@ -10,26 +10,27 @@ build:
   number: 0
 
 source:
-  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ github_version }}.zip
-  sha256: 23f88a70c6ee94998e08420a465f8497b6da561488ac1dc3f56335c9763064d0
+  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version
+    }}/{{ name }}-{{ github_version }}.zip
+  sha256: ca821ffb2a357a4ae15afd1c17848c4acd2ca905013183ad7ceb7b4e4b50643d
   patches:
-    - windows-bat-classpath-wildcard.patch  # [win]
+  - windows-bat-classpath-wildcard.patch    # [win]
 
 requirements:
   build:
-    - m2-patch  # [win]
+  - m2-patch    # [win]
   run:
-    - bioformats2raw-libs={{ PKG_VERSION }}-{{ PKG_BUILDNUM }}
-    - openjdk
+  - bioformats2raw-libs={{ PKG_VERSION }}-{{ PKG_BUILDNUM }}
+  - openjdk
 
 test:
   commands:
-    - bioformats2raw a.fake output
-    - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr
+  - bioformats2raw a.fake output
+  - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr
 
 extra:
   recipe-maintainers:
-    - ome
+  - ome
 
 about:
   home: https://www.glencoesoftware.com/
```

So the command completes but the substitution is incomplete.

This work possibly answers a maintenance question that was raised internally yesterday as the recipe currently available from the OME Conda channel is outdated. From the academically funded OME persective, the intent is still to maintain these recipes and track new bioformats2raw/raw2ometiff releases via automation? /cc @erindiel @mabruce @melissalinkert

2023-04-18 09:10 UTC, sbesson commented on scc/git.py
> +    KEY_GIT_VERSION = "git_version"
Assuming it's meant to be 
```suggestion
    KEY_GIT_VERSION = "github_version"
```

2023-04-18 09:20 UTC, sbesson commented
The last commit still fails with 

```
(base) sbesson@Sebastiens-MacBook-Pro-2 conda-bioformats2raw % ../scc/venv/bin/scc bump-version-conda
Traceback (most recent call last):
  File "/Users/sbesson/Documents/GitHub/scc/scc/main.py", line 64, in entry_point
    main("scc", items=[
  File "/Users/sbesson/Documents/GitHub/scc/venv/lib/python3.9/site-packages/yaclifw/framework.py", line 188, in main
    ns.func(ns)
  File "/Users/sbesson/Documents/GitHub/scc/scc/git.py", line 4133, in __call__
    msg = self.update_data(".", jinja2, latest_tag, sha256,
  File "/Users/sbesson/Documents/GitHub/scc/scc/git.py", line 4280, in update_data
    if data["package"][self.KEY_GIT_VERSION] and \
  File "/Users/sbesson/Documents/GitHub/scc/venv/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'github_version'
```
for me

2023-04-18 09:34 UTC, jburel commented
I will have a look at it later today

2023-04-18 11:34 UTC, jburel commented
Problem should now be solved. Also note https://github.com/ome/conda-bioformats2raw/pull/17

2023-04-18 11:50 UTC, sbesson reviewed
With the last commit, I have

```diff
commit 568d01d3028fe0555420030c1cebc598d8b83652 (HEAD)
Author: Sébastien Besson <sbesson@glencoesoftware.com>
Date:   Tue Apr 18 12:48:32 2023 +0100

    Update version to 0.6.1

diff --git a/bioformats2raw-libs/meta.yaml b/bioformats2raw-libs/meta.yaml
index ba1e8b0..dd10b22 100644
--- a/bioformats2raw-libs/meta.yaml
+++ b/bioformats2raw-libs/meta.yaml
@@ -1,6 +1,6 @@
 {% set name = "bioformats2raw-libs" %}
-{% set version = "0.5.0" %}
-{% set github_version = "0.5.0" %}
+{% set version = "0.6.1" %}
+{% set github_version = "0.6.1" %}
 
 package:
   name: "{{ name|lower }}"
@@ -11,17 +11,18 @@ build:
   noarch: generic
 
 source:
-  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version }}/bioformats2raw-{{ github_version }}.zip
-  sha256: 23f88a70c6ee94998e08420a465f8497b6da561488ac1dc3f56335c9763064d0
+  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version
+    }}/bioformats2raw-{{ github_version }}.zip
+  sha256: ca821ffb2a357a4ae15afd1c17848c4acd2ca905013183ad7ceb7b4e4b50643d
 
 # Leave the OS specific dependencies to the wrapper
 requirements:
   run:
-    - blosc
+  - blosc
 
 extra:
   recipe-maintainers:
-    - ome
+  - ome
 
 about:
   home: https://www.glencoesoftware.com/
diff --git a/bioformats2raw/meta.yaml b/bioformats2raw/meta.yaml
index 3fb45ef..150b3e0 100644
--- a/bioformats2raw/meta.yaml
+++ b/bioformats2raw/meta.yaml
@@ -1,6 +1,6 @@
 {% set name = "bioformats2raw" %}
-{% set version = "0.5.0" %}
-{% set github_version = "0.5.0" %}
+{% set version = "0.6.1" %}
+{% set github_version = "0.6.1" %}
 
 package:
   name: "{{ name|lower }}"
@@ -10,26 +10,27 @@ build:
   number: 0
 
 source:
-  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ github_version }}.zip
-  sha256: 23f88a70c6ee94998e08420a465f8497b6da561488ac1dc3f56335c9763064d0
+  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version
+    }}/{{ name }}-{{ github_version }}.zip
+  sha256: ca821ffb2a357a4ae15afd1c17848c4acd2ca905013183ad7ceb7b4e4b50643d
   patches:
-    - windows-bat-classpath-wildcard.patch  # [win]
+  - windows-bat-classpath-wildcard.patch    # [win]
 
 requirements:
   build:
-    - m2-patch  # [win]
+  - m2-patch    # [win]
   run:
-    - bioformats2raw-libs={{ PKG_VERSION }}-{{ PKG_BUILDNUM }}
-    - openjdk
+  - bioformats2raw-libs={{ PKG_VERSION }}-{{ PKG_BUILDNUM }}
+  - openjdk
 
 test:
   commands:
-    - bioformats2raw a.fake output
-    - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr
+  - bioformats2raw a.fake output
+  - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr
 
 extra:
   recipe-maintainers:
-    - ome
+  - ome
 
 about:
   home: https://www.glencoesoftware.com/
```

which looks sensible. Should this be tested against another recipe without the `github_version` metadata? Do you have a suggestion of an active recipe?

2023-04-18 12:11 UTC, jburel commented
This could be tested against https://github.com/ome/conda-bftools

2023-04-18 12:17 UTC, sbesson approved these changes
Using the current `conda-bftools` repository and this PR

```diff
commit e20102aab6b0f08c3fb89c948f03efb0e3a7f2e3 (HEAD -> master)
Author: Sébastien Besson <sbesson@glencoesoftware.com>
Date:   Tue Apr 18 13:16:06 2023 +0100

    Update version to 6.12.0

diff --git a/bftools-libs/meta.yaml b/bftools-libs/meta.yaml
index 5e786db..5dd96ff 100644
--- a/bftools-libs/meta.yaml
+++ b/bftools-libs/meta.yaml
@@ -1,4 +1,4 @@
-{% set version = "6.10.0" %}
+{% set version = "6.12.0" %}
 
 package:
   name: "bftools-libs"
@@ -10,7 +10,7 @@ build:
 
 source:
   url: https://downloads.openmicroscopy.org/bio-formats/{{ version }}/artifacts/bftools.zip
-  sha256: 4131438e6c2b8cefbd9c7795e3c42b68d32082d04426217dafd924ed974d1a9d
+  sha256: 5872db401a6f746e162af8b5b762502d03e5c7db80d97ba3b9fd9175da0ae69c
 
 extra:
   recipe-maintainers:
diff --git a/bftools/meta.yaml b/bftools/meta.yaml
index 1e5c8a2..d3aa22f 100644
--- a/bftools/meta.yaml
+++ b/bftools/meta.yaml
@@ -1,4 +1,4 @@
-{% set version = "6.10.0" %}
+{% set version = "6.12.0" %}
 
 package:
   name: "bftools"
@@ -9,7 +9,7 @@ build:
 
 source:
   url: https://downloads.openmicroscopy.org/bio-formats/{{ version }}/artifacts/bftools.zip
-  sha256: 4131438e6c2b8cefbd9c7795e3c42b68d32082d04426217dafd924ed974d1a9d
+  sha256: 5872db401a6f746e162af8b5b762502d03e5c7db80d97ba3b9fd9175da0ae69c
 
 requirements:
   run:
```

2023-04-19 06:11 UTC, jburel commented
no longer needed

2023-04-19 06:11 UTC, closed without merging